name = "Continuables"
uuid = "79afa230-ca09-11e8-120b-5decf7bf5e25"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "0.3.0"

[deps]
ASTParser = "3311a090-b55d-11e9-176d-dbdfc6a88253"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataTypesBasic = "83eed652-29e8-11e9-12da-a7c29d64ffc9"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SimpleMatch = "a3ae8450-d22f-11e9-3fe0-77240e25996f"
