name = "Continuables"
uuid = "79afa230-ca09-11e8-120b-5decf7bf5e25"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "0.2.1"

[deps]
ASTParser = "3311a090-b55d-11e9-176d-dbdfc6a88253"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DataTypesBasic = "83eed652-29e8-11e9-12da-a7c29d64ffc9"
ProxyInterface = "90c4b210-f34a-11e9-1a87-5d0d3aaf0cab"
SimpleMatch = "a3ae8450-d22f-11e9-3fe0-77240e25996f"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
